### ISSUE TITLE
Is this line necessary or desirable?

### ISSUE THREAD

**Issue by jbrucker** [Siripa-Maneein/ku-polls#52]
https://github.com/Siripa-Maneein/ku-polls/blob/aa379eb20c646285e50af880a5480c479302896b/polls/views.py#L110

In the previous statement you created a Vote.  `Vote.objects.create` also saves the Vote object to the database.
You didn't change the choice object so why save it?
Conceptually, a Vote should not change the Choice, right?

**Comment by Siripa-Maneein** [comment]
You're right. Now, I have fixed this in the ```fix-issues``` branch. Thank you.
