### ISSUE TITLE
Refactor and avoid iterating over choices

### ISSUE THREAD

**Issue by jbrucker** [Siripa-Maneein/ku-polls#53]
https://github.com/Siripa-Maneein/ku-polls/blob/aa379eb20c646285e50af880a5480c479302896b/polls/models.py#L40-L45

This code requires that many elements of choice_set be retrieved from the database and recreated as objects.
You should avoid writing "for" loops like this and instead use a Django query expression in a `filter` or `get` method call.

This code also adds *coupling* to User.  Before you added this code, the Question class was not coupled to User.

This code is called from the `vote` view.
In the `vote` view you know the question and the user.  
So you can use a Django query expression to access vote -> choice -> question, like in Python `vote.choice.question`

Use (for example, there are many ways) 
```python
# Find a vote matching both the question and user
Vote.objects.filter(choice__question = question, user=user)
```
You could make this a separate method or function since you call it many times.

The key knowledge here is using Django query expressions to traverse relationships.
Use two underscores, such as `choice__question` meaning: `vote.choice.questiion`
or `choice__id__lt=2` meaning `vote.choice.id < 2`.

**Comment by Siripa-Maneein** [comment]
Thank you for your explanation. I understand this better now. I have just fixed this in the ```fix-issues``` branch. I moved the get_voted_choice() to the views.py and in order to get the voted choice, I've changed the function to be the same as below.
```
def get_voted_choice(question, user):
    """Get a choice from the question that the user already voted."""
    try:
        return Vote.objects.get(choice__question=question, user=user).choice
    except Vote.DoesNotExist:
        return None
 ```

**Comment by jbrucker** [comment]
That's *much* simpler.  And good that you wrote it as a separate function instead of
complicating the vote() view.

There is one pathological case:  if a `get` query returns more than one result,
it will raise an exception.  That would mean a bug in our code (someone got 2 votes).
